"""empty message

Revision ID: 13a58cb137ec
Revises: cf1b5504da2d
Create Date: 2025-02-03 23:03:26.991677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a58cb137ec'
down_revision = 'cf1b5504da2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.String(length=80), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
